artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/mon28/Datasets/raw/main/rainfall-australia-data
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion/
  
data_validation:
  root_dir: artifacts/data_validation
  dataset_csv_file: artifacts/data_ingestion/weatherAUS.csv
  cleaned_data_filename: preprocessed_rainfall.csv

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_validation
  data_file: preprocessed_rainfall.csv
  transformed_filename: transformed_data.csv

model_training:
  model_path: artifacts/model_training
  model_name: cat_model.pkl
  data_path: artifacts/data_transformation
  data_file: transformed_data.csv